import { Webposter } from '@/components/Webposter'
import { prisma } from '@/lib/db'
import { revalidateTag } from 'next/cache'
import { notFound, redirect } from 'next/navigation'

export default async function Page({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined }
}) {
  if (searchParams['secret'] !== process.env.ADMIN_SECRET) {
    notFound()
  }

  if (!prisma) {
    return <div>Database is not connected</div>
  }

  const unpublishedWebposters = await prisma.webposter.findMany({
    where: {
      published: false,
    },
    orderBy: {
      createdAt: 'desc',
    },
    take: 16,
  })

  const publishedWebposters = await prisma.webposter.findMany({
    where: {
      published: true,
    },
    orderBy: {
      createdAt: 'desc',
    },
    take: 16,
  })

  const publishWebposter = async (formData: FormData) => {
    'use server'

    await prisma?.webposter.update({
      where: { id: formData.get('id') as string },
      data: { published: true },
    })

    revalidateTag('latestWebposters')
    redirect(`/admin?secret=${formData.get('secret') as string}`)
  }

  const unpublishWebposter = async (formData: FormData) => {
    'use server'

    await prisma?.webposter.update({
      where: { id: formData.get('id') as string },
      data: { published: false },
    })

    revalidateTag('latestWebposters')
    redirect(`/admin?secret=${formData.get('secret') as string}`)
  }

  return (
    <main className="flex min-h-[100svh] flex-col items-center justify-around gap-4 px-4 py-6">
      <div>
        <div className="mb-8 flex flex-col gap-2">
          <h4 className="text-5xl font-semibold md:text-6xl">
            Unpublished newest Posters
          </h4>
          <p className="font-mono text-lg text-muted-foreground">
            Some unpublished posters generated by the community.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2 md:grid-cols-3 md:gap-y-10 lg:grid-cols-4">
          {unpublishedWebposters.map((webposter) => (
            <form key={webposter.id} action={publishWebposter}>
              <input type="hidden" name="id" value={webposter.id} />
              <input
                type="hidden"
                name="secret"
                value={searchParams['secret']}
              />
              <button type="submit">
                <Webposter webposter={webposter} unoptimized />
              </button>
            </form>
          ))}
        </div>
      </div>

      <div>
        <div className="mb-8 flex flex-col gap-2">
          <h4 className="text-5xl font-semibold md:text-6xl">
            Published newest Posters
          </h4>
          <p className="font-mono text-lg text-muted-foreground">
            Some published posters generated by the community.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2 md:grid-cols-3 md:gap-y-10 lg:grid-cols-4">
          {publishedWebposters.map((webposter) => (
            <form key={webposter.id} action={unpublishWebposter}>
              <input type="hidden" name="id" value={webposter.id} />
              <input
                type="hidden"
                name="secret"
                value={searchParams['secret']}
              />
              <button type="submit">
                <Webposter webposter={webposter} unoptimized />
              </button>
            </form>
          ))}
        </div>
      </div>
    </main>
  )
}
