import { Webposter } from '@/components/Webposter'
import { prisma } from '@/lib/db'
import { unstable_cache } from 'next/cache'
import Link from 'next/link'

const getLatestMovieposters = unstable_cache(
  async () => {
    const webposters = await prisma.webposter.findMany({
      where: {
        published: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
      take: 16,
      select: {
        url: true,
        imageUrl: true,
      },
    })
    return webposters
  },
  ['latestWebposters'],
  {
    revalidate: 60,
    tags: ['latestWebposters'],
  }
)

export const Explore = async () => {
  const webposters = await getLatestMovieposters()

  return (
    <div>
      <div className="mb-8 flex flex-col gap-2">
        <h4 className="text-5xl font-semibold md:text-6xl">Explore</h4>
        <p className="font-mono text-lg text-muted-foreground">
          Here are some of the latest posters generated by the community.
        </p>
      </div>
      <div className="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2 md:grid-cols-3 md:gap-y-10 lg:grid-cols-4">
        {webposters.map((webposter) => (
          <Link href={`/${webposter.url}`} key={webposter.url}>
            <Webposter webposter={webposter} />
          </Link>
        ))}
      </div>
    </div>
  )
}
